last_update = 1669686178816
api_url = "https://api.playit.cloud/agent"
ping_target_addresses = ["23.133.216.1:5530", "ping.playit.gg"]
control_address = "control.ply.gg"
refresh_from_api = true
api_refresh_rate = 5000
ping_interval = 5000
secret_key = "c4e8d4cdba76d761442663bedd96b8828eba6bd75581b6641205fb14d75be2af"

[[mappings]]
name = "Minecraft Server"
proto = "tcp"
tunnel_ip = "147.185.221.180"
tunnel_from_port = 34076
local_port = 25563
