last_update = 1670535890819
api_url = "https://api.playit.cloud/agent"
ping_target_addresses = ["23.133.216.1:5530", "ping.playit.gg"]
control_address = "control.ply.gg"
refresh_from_api = true
api_refresh_rate = 5000
ping_interval = 5000
secret_key = "c0b7d001f431823aeba0745479d07395ffa223d253f432fa820c236919d5c4e4"

[[mappings]]
name = "Minecraft Server"
proto = "tcp"
tunnel_ip = "147.185.221.180"
tunnel_from_port = 34076
local_port = 25563
